language: python
os: linux

jobs:
  include:
    - os: linux
      python: 3.8
      env: BUILDENV=focal

branches:
  only:
    - master

services:
  - docker

before_install:
  - sudo /etc/init.d/postgresql stop
  - sudo /etc/init.d/ssh stop
  - docker build -t minicloud_focal build/focal

install:
  - docker run --network host --name cloud_on_focal minicloud_focal

script:
  - sleep 60
  - docker ps
  - docker ps -a
  - docker exec cloud_on_focal sh -c "id -a"
  - curl -I localhost/login 2> /dev/null | grep '501'
  - curl -I localhost:8290 2> /dev/null | grep '401'

addons:
  apt:
    packages:
      - docker-ce
