language: python
python:
  - 3.6
  - 3.7
  - 3.8

branches:
  only:
    - master

services:
  - docker

before_install:
  - docker build -t minicloud .
  - docker run --network host -d -P --name cloud minicloud:latest

script:
  - curl -I localhost/login 2> /dev/null | grep '501'

addons:
  apt:
    packages:
      - docker-ce
