language: python
python:
  - 3.6
  - 3.7
  - 3.8

branches:
  only:
    - master

services:
  - docker

before_install:
  - docker build -t minicloud .
  - docker run -d -P --name cloud minicloud:latest

addons:
  apt:
    packages:
      - docker-ce
