language: python
python:
  - 3.6
  - 3.7
  - 3.8

branches:
  only:
    - master

services:
  - docker

before_install:
  - docker build -t minicloud_focal builds/focal
  - docker run --network host -d -P --name cloud_on_focal minicloud_focal

script:
  - sleep 10

addons:
  apt:
    packages:
      - docker-ce
