language: generic
os: linux

branches:
  only:
    - master

services:
  - docker

before_script:
  - sudo /etc/init.d/postgresql stop
  - sudo /etc/init.d/ssh stop
  - docker build -t minicloud_centos8 build/centos8
  - docker build -t minicloud_buster build/buster
  - docker build -t minicloud_focal build/focal

script:
  - /bin/bash build/centos8/run.sh
  - /bin/bash build/buster/run.sh
  - /bin/bash build/focal/run.sh

after_script:
  - echo 'Finished'

addons:
  apt:
    packages:
      - docker-ce
