language: python
python:
  - 3.6
  - 3.7
  - 3.8

branches:
  only:
    - master

services:
  - docker

before_install:
  - docker build -t minicloud_focal builds/focal
  - docker run --network host -d -P --name cloud_on_focal minicloud_focal

script:
  - curl -I localhost/login 2> /dev/null | grep '501'
  - curl -I localhost:8290 2> /dev/null | grep '401'

addons:
  apt:
    packages:
      - docker-ce
