MIME_SUFFIX = { 'text/plain': 'txt'
              , 'text/x-python': 'rb'
              , 'application/x-ruby': 'rb'
              , 'text/x-haskell': 'hs'
              , 'text/x-csrc': 'c'
              , 'application/x-javascript': 'js'
              , 'application/x-shellscript': 'sh'
              , 'application/octet-stream': 'part'
              , 'text/html': 'html'
              , 'text/css': 'css'
              , 'text/markdown': 'md'
              , 'font/ttf': 'ttf'
              , 'font/otf': 'otf'
              , 'application/pdf': 'pdf'
              , 'application/x-tar': 'tar'
              , 'application/x-xz': 'xz'
              , 'application/zip': 'zip'
              , 'application/gzip': 'gzip'
              , 'image/jpeg': 'jpg'
              , 'image/png': 'png'
              , 'image/svg+xml': 'svg'
              , 'image/x-icon': 'ico'
              , 'image/webp': 'webp'
              , 'audio/mpeg': 'mp3'
              , 'audio/ogg': 'oga'
              , 'audio/x-wav': 'wav'
              , 'audio/x-mpegurl': 'm3u'
              , 'audio/opus': 'opus'
              , 'audio/webm': 'webm'
              , 'video/avi': 'avi'
              , 'video/mp4': 'mp4'
              , 'video/ogg': 'ogv'
              , 'video/webm': 'webm'
              }

MIME_TYPES = { 'audio': [ 'audio/aac'
                        , 'audio/mpeg'
                        , 'audio/ogg'
                        , 'audio/x-wav'
                        , 'audio/x-mpegurl'
                        , 'audio/opus'
                        ]

             , 'video': [ 'video/avi'
                        , 'video/mp4'
                        , 'video/ogg'
                        , 'video/webm'
                        ]
             }
